### PR TITLE
Fix 0.business_days and 0.business_hours calculation

### PR DESCRIPTION
**Pull request by mlen**
Fixes https://github.com/bokmann/business_time/issues/164

### CODE REVIEW

**Comment by bokmann** [comment]
Excellent work.  Beautiful pull request.  Thank you!

**Comment by mlen** [comment]
@bokmann thanks for merging! Could you please tag a new release and publish it on rubygems?

**Comment by bokmann** [comment]
I'll do shortly.

**Comment by jaredbeck** [comment]
Please cut a release with this fix, thanks!

**Comment by jaredbeck** [comment]
@bokmann Two month ping. Please cut a release with this fix, thanks!

**Comment by jaredbeck** [comment]
@bokmann Three month ping. Please cut a release with this fix, thanks!

If I could help with a release, I would, but you're the only one who can.

**Comment by jaredbeck** [comment]
Released in 0.9.3, on 2017-11-04. Thanks David.

**Pull request merged**
