### PR TITLE
Master

### PR DESCRIPTION
**Pull request by freestyler**

### CODE REVIEW

**Comment by bokmann** [comment]
So I can't automatically merge this now, but there is no description with this feature.  I think I grok the intent from the tests, but can you clarify what this is about?

**Comment by freestyler** [comment]
In such case if any workdays are at the weekend, you can add them, too.

Shall I complete Readme file or do you handle it?

**Comment by bokmann** [comment]
but you could already add a weekend day to your work week like this:

BusinessTime::Config.work_week = [:sun, :mon, :tue, :wed, :thu]

What do you need this for?

**Comment by bokmann** [comment]
Oh I see - this is a one-off... an anti-holiday.

In the 5+ years I've used this in production, I've never needed functionality like this... in fact, it kinda goes against how I use this gem for calculating due dates in workflow situations... if people work the weekend, its to catch up on work... if that were baked into due date calculations, they wouldn't be able to 'catch up.

Do you have a real use case for this? Adding it won't preclude my use case, but I'm always striving for simpler code...

**Comment by freestyler** [comment]
http://www.rsmdtm.hu/scheduled-working-time-around-official-holidays-in-2015-141002143508

**Comment by freestyler** [comment]
In Hungary, if there is a national holiday on Tuesday or on Thursday, we have a 4-day-long holiday. But we have to work on a Saturday one or two weeks before this long weekend.

**Pull request closed without merging**
