### PR TITLE
Fix methods after and before when date is on weekend

### PR DESCRIPTION
**Pull request by dynaum**

### CODE REVIEW

**Comment by dynaum** [comment]
:question:

**Comment by Philhawk** [comment]
+1

**Comment by jamesmartin** [comment]
+1

**Comment by bokmann** [comment]
I don't understand why people want this.  Let me talk through the original intent (and whats required by the legal framework this gem was originally written for).

Business hours only count during, well, business hours.  That is, if legally, we have 1 business day to perform a task, and that task arrives on Saturday, outside of business hours, the official clock doesn't start until the business opens Monday morning.  One business day after would be Tuesday morning.

This path seems to think that Monday morning would be one business day after Saturday, and I don't see how you can consider that correct if Saturday nor Sunday are business days.  I'm willing to talk about it though, as it seems like there is a requirement here we are overloading.

**Comment by jamesmartin** [comment]
@bokmann thanks for the explanation. I think I understand this perspective a little better now.

Here's an example of what we were trying to achieve:

Let's say we want to allow a person to choose a business day in the future, to receive a phone call from a company that operates a call centre from Monday to Friday. Given a "current day", we want to show a list of three consecutive "business" days to choose from.

When the "current day" is Thursday, we expect the next three consecutive business days to be Friday, Monday and Tuesday. But if we use the `#after` method (and iterate the date), we'll end up with Friday, Tuesday and Wednesday.

Given your explanation, I think we were trying to use the `#after` method to achieve something for which it was never intended.

**Comment by sahilchopra** [comment]
+1

**Comment by AAlvarez90** [comment]
I have a perfect example to support why the logic should change in the weekends. As of October 9th, 2016, I am expecting a product that is being delivered by UPS. The delivery date is set to be October 11th which is a Tuesday. With the current logic, 2 business days from now would be a Wednesday, however, this billionaire company thinks otherwise. 

image

As you can see, they say that will be delivered by the end-of-day tuesday, however, we all know that that's not always the case, it all depends on the route of the driver. UPS is considering monday as 1 business day and tuesday as another, but in tuesday things will happen, not on wednesday.

**Comment by bokmann** [comment]
In your example. the clock started ticking when it shipped Friday.

Friday + 1 == Monday
Friday + 2 == Tuesday

**Comment by AAlvarez90** [comment]
@bokmann Unfortunately for me, they shipped the package over a week ago. I just provided the information that could be used in this case. If you could make this configurable would be awesome, that way, people can decide which logic fits their needs: current or requested logic.

**Comment by bokmann** [comment]
This is operating as intended, and as stated in the readme and original mission in the project, this is meant to be a solution for a particular domain, not a 'configure-all-the-things' project.  You are welcome to fork the project and use it however you like.

**Pull request closed without merging**
