### PR TITLE
added sorted_set gem as dependency to use with ruby 3.0.0

### PR DESCRIPTION
**Pull request by tilhoft**

### CODE REVIEW

**Comment by bmalets** [comment]
Let's remove old ruby 2.2.2 in Travis CI settings, and add support of rubies 2.5.0, 2.6.0, 2.7.0 and 3.0.0 

@tilhoft please merge my Pull Request https://github.com/tilhoft/business_time/pull/1 - it will fix your Travis build here 😉

And do not forget to add line `## 1.0.0 2021-11-XX` to `CHANGELOG.md` file.

**Review by bmalets — CHANGES_REQUESTED** [review]
- Build didn't pass
- no release comments in `CHANGELOG.md`

**Comment by beanieboi** [comment]
FYI: I'm maintaining a fork with Ruby 3 compatibility until we get some movement here. if you have urgent needs feel free to use the fork. You can see the changes to get full Ruby 3 compatibility here: https://github.com/beanieboi/business_time/pull/2 and https://github.com/beanieboi/business_time/pull/3

Fork: https://github.com/beanieboi/business_time

**Comment by rmm5t** [comment]
I've got a version of this with a fully passing build matrix as a Github action at #203

**Review by J-Vin — APPROVED** [review]

**Pull request closed without merging**
