### PR TITLE
Allow passing holidays with each invocation.

### PR DESCRIPTION
**Pull request by mstate**
Modified code, test and documentation to allow passing a holiday or array of holidays with each invocation.  This is particularly useful when dealing with potentially different regional holidays during each invocations.

### CODE REVIEW

**Comment by bokmann** [comment]
Wow... I like this solution to a problem I've had (calculating backwards after snow days have happened), and it was less impactful that I would have considered.

It has a merge conflict with another pull I just merged, but if you resolve that it'll go into the next version!

Thanks for the first-time commit!  Don't forget to add yourself as a contributor to the readme!

**Comment by RST-J** [comment]
We recently had a problem with a local holiday in our region that does not exist in other regions of Germany. It would be solvable with `BusinessTime::Config.with` but we were not aware of that method and the solution implemented here is less verbose.

Inspired by this I thought of an direct integration of the `holidays` gem into `business_time`. But I am not sure whether you would be up for it @bokmann? Reading the Not-Todo section and the following one about stability and change suggest rather not. But I thought I'd ask first before considering doing it in a fork.

**Comment by Laykou** [comment]
Do you think this could be merged, please?

**Comment by rmm5t** [comment]
> Do you think this could be merged, please?

@Laykou This PR has merge conflicts that would need to be resolved first.

**Comment by Laykou** [comment]
@mstate Would you be willing to resolve the conflicts, please?

**Comment by cadenforrest** [comment]
I took a stab at resolving the conflicts in https://github.com/bokmann/business_time/pull/217

**Pull request closed without merging**
